import { UnitInfo, Lesson, Lab, FlashcardItem, FormulaItem, UserStats } from '@/types';

export const UNITS_DATA: UnitInfo[] = [
  {
    id: 'unit-1',
    unitNumber: 1,
    title: 'Foundations & Exploratory Data Analysis',
    shortTitle: 'EDA & Data Foundations',
    description: 'Master data representations, summary statistics, univariate & multivariate distributions, data cleaning pipelines, and visual analysis.',
    accentColor: '#F4A58A',
    colorTokens: {
      primary: '#F4A58A',
      soft: '#FCE5DC',
      border: '#EFC0B0',
      text: '#9E513B',
    },
    accentClass: 'unit-1',
    topics: ['Data Types & Encodings', 'Descriptive Statistics', 'Outlier Detection', 'Pandas & NumPy Pipelines', 'Visualization Principles'],
    estimatedHours: 12,
    totalLessons: 10,
    totalLabs: 4,
    totalQuizzes: 1,
    progressPercent: 0,
    prerequisites: ['Basic Python Syntax'],
  },
  {
    id: 'unit-2',
    unitNumber: 2,
    title: 'Linear Algebra & Vectors',
    shortTitle: 'Vectors & Linear Spaces',
    description: 'Understand vector spaces, geometric vector operations, dot products, vector projections, orthogonality, and Euclidean norms.',
    accentColor: '#91B9E8',
    colorTokens: {
      primary: '#91B9E8',
      soft: '#E5EFFB',
      border: '#B9D1EE',
      text: '#416B9E',
    },
    accentClass: 'unit-2',
    topics: ['Vector Spaces & Subspaces', 'Linear Independence', 'Dot Product & Cosine Similarity', 'Orthogonal Projections', 'Vector Norms (L1, L2, L∞)'],
    estimatedHours: 14,
    totalLessons: 10,
    totalLabs: 4,
    totalQuizzes: 1,
    progressPercent: 0,
    prerequisites: ['Unit 1: Foundations', 'High School Algebra'],
  },
  {
    id: 'unit-3',
    unitNumber: 3,
    title: 'Matrices & Determinants',
    shortTitle: 'Matrices & Transformations',
    description: 'Explore linear transformations, matrix inverses, determinants, rank-nullity theorem, eigenvalues, eigenvectors, and SVD foundations.',
    accentColor: '#8FC7A3',
    colorTokens: {
      primary: '#8FC7A3',
      soft: '#E5F3E9',
      border: '#B8DCC3',
      text: '#3F7951',
    },
    accentClass: 'unit-3',
    topics: ['Matrix Multiplication Mechanics', 'Determinants & Area Scaling', 'Matrix Inverses & Condition Number', 'Eigenvalues & Eigenvectors', 'Principal Component Analysis (PCA)'],
    estimatedHours: 16,
    totalLessons: 10,
    totalLabs: 4,
    totalQuizzes: 1,
    progressPercent: 0,
    prerequisites: ['Unit 2: Linear Algebra & Vectors'],
  },
  {
    id: 'unit-4',
    unitNumber: 4,
    title: 'Probability & Statistics',
    shortTitle: 'Probability & Inference',
    description: 'Learn probability axioms, conditional probability, Bayes theorem, probability distributions, central limit theorem, and hypothesis testing.',
    accentColor: '#B7A3E3',
    colorTokens: {
      primary: '#B7A3E3',
      soft: '#EEE9F8',
      border: '#CFC2EA',
      text: '#68539A',
    },
    accentClass: 'unit-4',
    topics: ['Probability Axioms & Combinatorics', 'Bayes’ Theorem & Prior/Posterior', 'Discrete & Continuous Distributions', 'Central Limit Theorem & Sampling', 'Hypothesis Testing & p-values'],
    estimatedHours: 18,
    totalLessons: 10,
    totalLabs: 4,
    totalQuizzes: 1,
    progressPercent: 0,
    prerequisites: ['Unit 1: Foundations', 'Calculus Basics'],
  },
  {
    id: 'unit-5',
    unitNumber: 5,
    title: 'Regression Analysis',
    shortTitle: 'Regression & Optimization',
    description: 'Formulate ordinary least squares (OLS), cost functions, gradient descent optimization, multivariate regression, and regularization (Ridge/Lasso).',
    accentColor: '#E8C878',
    colorTokens: {
      primary: '#E8C878',
      soft: '#FAF2D8',
      border: '#EBD99A',
      text: '#806A28',
    },
    accentClass: 'unit-5',
    topics: ['Simple Linear Regression', 'Least Squares & SSE', 'Residual Diagnostics & RMSE', 'Multiple Linear Regression', 'Polynomial Regression', 'Ridge & Lasso Regularization'],
    estimatedHours: 16,
    totalLessons: 10,
    totalLabs: 4,
    totalQuizzes: 1,
    progressPercent: 0,
    prerequisites: ['Unit 2: Vectors', 'Unit 3: Matrices', 'Unit 4: Probability'],
  },
  {
    id: 'unit-6',
    unitNumber: 6,
    title: 'Classification & Machine Learning',
    shortTitle: 'Classification Models',
    description: 'Understand logistic regression, decision boundaries, k-Nearest Neighbors, decision trees, cross-validation, and classification performance metrics.',
    accentColor: '#D99AAF',
    colorTokens: {
      primary: '#D99AAF',
      soft: '#F6E5EB',
      border: '#E5BBC9',
      text: '#8A4E63',
    },
    accentClass: 'unit-6',
    topics: ['Supervised Classification', 'Logistic Regression & Sigmoid', 'Decision Boundaries', 'k-Nearest Neighbors', 'Decision Trees', 'Model Evaluation & ROC-AUC'],
    estimatedHours: 18,
    totalLessons: 10,
    totalLabs: 4,
    totalQuizzes: 1,
    progressPercent: 0,
    prerequisites: ['Unit 2: Vectors', 'Unit 3: Matrices', 'Unit 4: Probability', 'Unit 5: Regression'],
  },
];

export const SAMPLE_LESSONS: Lesson[] = [
  {
    id: 'les-1-1',
    unitId: 'unit-1',
    title: 'Introduction to Scientific Data Formats',
    description: 'Learn tabular, structured, and unstructured data representations in memory.',
    durationMinutes: 15,
    completed: true,
    order: 1,
    type: 'concept',
  },
  {
    id: 'les-1-2',
    unitId: 'unit-1',
    title: 'Descriptive Statistics & Measures of Spread',
    description: 'Calculate mean, median, IQR, standard deviation, variance, and skewness.',
    durationMinutes: 25,
    completed: true,
    order: 2,
    type: 'derivation',
  },
  {
    id: 'les-1-3',
    unitId: 'unit-1',
    title: 'Visualizing Distributions: Histograms & KDEs',
    description: 'Construct informative histograms, density curves, and box plots with standard aesthetics.',
    durationMinutes: 20,
    completed: false,
    order: 3,
    type: 'interactive',
  },
  {
    id: 'les-1-4',
    unitId: 'unit-1',
    title: 'Robust Outlier Detection Algorithms',
    description: 'Implement Z-score, Tukey IQR fences, and Isolation Forests on realistic datasets.',
    durationMinutes: 30,
    completed: false,
    order: 4,
    type: 'code',
  },
];

export const SAMPLE_LABS: Lab[] = [
  {
    id: 'lab-1',
    unitId: 'unit-1',
    title: 'Exploratory Data Analysis on Real-World Sensors',
    description: 'Clean sensor timeseries data, handle missing timestamps, and identify anomalies.',
    difficulty: 'Beginner',
    durationMinutes: 45,
    completed: true,
    tags: ['Pandas', 'EDA', 'Cleaning'],
  },
  {
    id: 'lab-2',
    unitId: 'unit-2',
    title: 'Interactive Vector Transformation Playground',
    description: 'Visualize vector additions, dot products, and projections on dynamic 2D coordinates.',
    difficulty: 'Intermediate',
    durationMinutes: 35,
    completed: false,
    tags: ['Linear Algebra', 'Vectors', 'Visualization'],
  },
  {
    id: 'lab-3',
    unitId: 'unit-3',
    title: 'Eigenvalue Decomposition & Image Compression',
    description: 'Perform PCA and SVD on matrix pixel arrays to observe rank reduction.',
    difficulty: 'Advanced',
    durationMinutes: 50,
    completed: false,
    tags: ['PCA', 'Eigenvalues', 'SVD'],
  },
];

export const SAMPLE_FORMULAS: FormulaItem[] = [
  {
    id: 'form-1',
    unitId: 'unit-2',
    title: 'Euclidean Dot Product',
    latex: '\\mathbf{u} \\cdot \\mathbf{v} = \\sum_{i=1}^n u_i v_i = \\|\\mathbf{u}\\| \\|\\mathbf{v}\\| \\cos(\\theta)',
    description: 'Measures directional alignment and magnitude projection between two vectors in n-dimensional space.',
    variables: [
      { symbol: '\\mathbf{u}, \\mathbf{v}', meaning: 'Input vectors in Euclidean space' },
      { symbol: '\\theta', meaning: 'Angle between the two vectors' },
      { symbol: '\\|\\mathbf{u}\\|', meaning: 'L2 Euclidean norm of vector u' },
    ],
  },
  {
    id: 'form-2',
    unitId: 'unit-5',
    title: 'Ordinary Least Squares (OLS) Closed Form',
    latex: '\\hat{\\beta} = (\\mathbf{X}^T \\mathbf{X})^{-1} \\mathbf{X}^T \\mathbf{y}',
    description: 'Analytical solution minimizing the sum of squared residuals for linear regression.',
    variables: [
      { symbol: '\\mathbf{X}', meaning: 'Feature matrix of shape (N, D)' },
      { symbol: '\\mathbf{y}', meaning: 'Target observation vector of shape (N, 1)' },
      { symbol: '\\hat{\\beta}', meaning: 'Optimal regression weights' },
    ],
  },
];

export const SAMPLE_FLASHCARDS: FlashcardItem[] = [
  {
    id: 'fc-1',
    unitId: 'unit-2',
    front: 'What does it mean for two vectors to be orthogonal?',
    back: 'Two vectors are orthogonal if their inner (dot) product equals zero: u · v = 0, meaning they are at a 90° angle in Euclidean space.',
    tag: 'Linear Algebra',
  },
  {
    id: 'fc-2',
    unitId: 'unit-4',
    front: 'State Bayes’ Theorem formula.',
    back: 'P(A|B) = [P(B|A) * P(A)] / P(B), describing the probability of an event based on prior knowledge of conditions.',
    formula: 'P(A|B) = \\frac{P(B|A) P(A)}{P(B)}',
    tag: 'Probability',
  },
];

export const MOCK_USER_STATS: UserStats = {
  unitsCompleted: 0,
  lessonsCompleted: 8,
  labsCompleted: 3,
  quizzesCompleted: 4,
  overallProgress: 20,
  currentStreakDays: 5,
  recentActivity: [
    {
      title: 'Completed: Descriptive Statistics & Measures of Spread',
      unitNumber: 1,
      timestamp: '2 hours ago',
      type: 'lesson',
    },
    {
      title: 'Finished: Exploratory Data Analysis on Real-World Sensors',
      unitNumber: 1,
      timestamp: 'Yesterday',
      type: 'lab',
    },
    {
      title: 'Passed Quiz: Vector Operations & Dot Products (100%)',
      unitNumber: 2,
      timestamp: '3 days ago',
      type: 'quiz',
    },
  ],
};
